#!/bin/bash          

cat x00 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x00.subj.namespace &
cat x01 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x01.subj.namespace &
cat x02 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x02.subj.namespace &
cat x03 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x03.subj.namespace &
cat x04 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x04.subj.namespace &
cat x05 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x05.subj.namespace &
cat x06 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x06.subj.namespace &
cat x07 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x07.subj.namespace &
cat x08 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x08.subj.namespace &
cat x09 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x09.subj.namespace &
cat x10 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x10.subj.namespace &
cat x11 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x11.subj.namespace &
cat x12 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x12.subj.namespace &
cat x13 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x13.subj.namespace &
cat x14 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x14.subj.namespace &
cat x15 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x15.subj.namespace &
cat x16 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x16.subj.namespace &
cat x17 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x17.subj.namespace &
cat x18 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x18.subj.namespace &
cat x19 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x19.subj.namespace &
cat x20 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x20.subj.namespace &
cat x21 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x21.subj.namespace &
cat x22 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x22.subj.namespace &
cat x23 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x23.subj.namespace &
cat x24 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x24.subj.namespace &
cat x25 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x25.subj.namespace &
cat x26 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x26.subj.namespace &
cat x27 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x27.subj.namespace &
cat x28 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x28.subj.namespace &
cat x29 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x29.subj.namespace &
cat x30 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x30.subj.namespace &
cat x31 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x31.subj.namespace &
cat x32 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x32.subj.namespace &
cat x33 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x33.subj.namespace &
cat x34 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x34.subj.namespace &
cat x35 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x35.subj.namespace &
cat x36 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x36.subj.namespace &
cat x37 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x37.subj.namespace &
cat x38 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x38.subj.namespace &
cat x39 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x39.subj.namespace &
cat x40 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x40.subj.namespace &
cat x41 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x41.subj.namespace &
cat x42 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x42.subj.namespace &
cat x43 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x43.subj.namespace &
cat x44 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x44.subj.namespace &
cat x45 | sed -n 's;<\([^>]*\)/[^>]*>.*;\1;p' > x45.subj.namespace &
